------CAU8------
SELECT GIA
FROM SANPHAM
WHERE GIA >= 500
------CAU9------
SELECT MAKH, SL
FROM HOADON, CTHD
WHERE HOADON.SOHD = CTHD.SOHD AND SL >= 1
------CAU10------
SELECT MAKH, NGSINH, NGDK
FROM KHACHHANG
WHERE YEAR(NGDK) > YEAR(NGSINH)
------CAU11------
SELECT KHACHHANG.MAKH, NGHD, NGDK
FROM KHACHHANG, HOADON
WHERE KHACHHANG.MAKH = HOADON.MAKH AND DAY(NGHD) >= DAY(NGDK)
------CAU12------
SELECT NHANVIEN.MANV, NGVL, NGHD
FROM NHANVIEN, HOADON
WHERE NHANVIEN.MANV = HOADON.MANV AND DAY(NGHD) >= DAY(NGVL)
------CAU13------
SELECT HOADON.SOHD
FROM HOADON, CTHD
WHERE HOADON.SOHD = CTHD.SOHD
------CAU14------
DECLARE @TONGTIEN FLOAT;
SET @TONGTIEN = (SELECT SL * GIA FROM CTHD, SANPHAM)
SELECT HOADON.SOHD, @TONGTIEN AS 'TONGTIEN'
FROM HOADON, CTHD
WHERE HOADON.SOHD = CTHD.SOHD
------CAU15------
DECLARE @DOANHSO FLOAT;
SET @DOANHSO = (SELECT SUM(TRIGIA) FROM HOADON)
SELECT KHACHHANG.MAKH, SOHD, @DOANHSO AS 'DOANHSO'
FROM KHACHHANG, HOADON
WHERE KHACHHANG.MAKH = HOADON.MAKH